[package]
name = "kv_cab"
version = "0.4.5"
authors = ["shockham <samuel.hockham@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shockham/kv_cab"
homepage = "https://github.com/shockham/kv_cab"
documentation = "https://docs.rs/kv_cab"
description = "Simple persistent generic HashMap/Key-value store"

[dependencies]
bincode = "0.6"
rustc-serialize = "0.3"
log = "0.3"
